### ISSUE TITLE
Add Delete Task functionality 

### ISSUE THREAD

**Issue by vj-codes** [bluelearn-open-source/Lets-Blue-The-Hacktoberfest#8]

**Comment by lakshyaagr1105** [comment]
Hey @vj-codes , I am Lakshya and I am a FrontEnd Developer, can you please assign me this project, i am highly interested

**Comment by vj-codes** [comment]
@lakshyaagr1105 assigning you.
Happy coding!

**Comment by VG-1** [comment]
hey @lakshyaagr1105 are you working on it?

**Comment by lakshyaagr1105** [comment]
I did a pull request with the repository containing delete functionality

**Comment by lakshyaagr1105** [comment]
@VG-1
